version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: less
    versions:
    - 4.0.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.6
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
  - dependency-name: postcss
    versions:
    - 8.2.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
