language: node_js
node_js:
  - 8
  - 10
cache: yarn

script:
  - yarn lint
  - yarn stylelint
  - yarn test:cover
  - yarn prod || yarn prod # Have to run twice for scss.d.ts modules to be picked up

notifications:
  email: false
