language: node_js
node_js:
  - 8
  - 10
cache: yarn

script:
  - yarn lint
  - yarn stylelint
  - yarn test:cover
  - yarn webpack --config webpack.development.config.ts
  - yarn prod

notifications:
  email: false
