language: node_js
node_js:
  - 8
  - 10
cache: yarn

script:
  - yarn lint
  - yarn stylelint
  - yarn test:cover
  - yarn dev & wait-on http://localhost:1337
  - yarn test:e2e --record --key 5511ac18-4b91-469c-819b-09c0ab7ce8af
  - yarn prod

notifications:
  email: false

before_install:
  - yarn --frozen-lockfile