language: node_js
node_js:
  - 8
  - 10
cache: yarn

script:
  - yarn lint
  - yarn stylelint
  - yarn test:cover
  - yarn dev & wait-on http://localhost:1337
  - yarn test:e2e
  - yarn prod

notifications:
  email: false

before_install:
  - yarn --frozen-lockfile